version: '3.4'

services:

  dsrnetschool_postgresql:
    image: postgres:14.1
    
  dsrnetschool_redis:
    image: redis

  dsrnetschool_api:
    image: ${DOCKER_REGISTRY-}dsrnetschoolapi
    build:
      context: .
      dockerfile: Systems/Api/DSRNetSchool.Api/Dockerfile
    depends_on:
      - dsrnetschool_postgresql
      - dsrnetschool_redis

  dsrnetschool_identity:
    image: ${DOCKER_REGISTRY-}dsrnetschoolidentity
    build:
      context: .
      dockerfile: Systems/Identity/DSRNetSchool.Identity/Dockerfile
    depends_on: #Dependence (If they are not connected, then this one does not make sense)
      - dsrnetschool_postgresql
      - dsrnetschool_redis
      - dsrnetschool_api

#docker-compose build
#docker-compose up
#^C